function [fitresult, gof] = two_exp_fit(a)
%CREATEFIT(A)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: a
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-Dec-2019 13:15:37


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], a );

% Set up fittype and options.
ft = fittype( 'a*exp(-b*x)+c*exp(-d*x)+f', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
%opts.Lower = [0 -0.2 0 -0.2 -5000000]; %-200

const=5000;

opts.Lower = [0 -0.2 0 -0.2 -const]; %-200
%opts.StartPoint = [3*a(1)/2 -log(a(5)/a(4)) a(1)/2 -log(a(5)/a(4)) 0];
opts.MaxIter = 50000;

opts.StartPoint = [1.1*a(1) -log(a(5)/a(4)) a(1)*0.5 -log(a(5)/a(4)) 0];
%opts.StartPoint = [1.02*a(1) -log(a(5)/a(4)) 0 -log(a(5)/a(4)) 0];


%opts.StartPoint = [2*a(1) -log(a(5)/a(4)) 0 -log(a(5)/a(4)) 0];
%opts.Upper = [2*a(1) 1.2  1.5*a(1) 1.2 50000000];
opts.Upper = [2*a(1) 1.2  1.5*a(1) 1.2 const];
opts.weights=[1, ones(1,length(a)-1)];


opts.Robust = 'Bisquare';



% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% %Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'a', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% ylabel a
% grid on





